trigger:
  branches:
    include:
    - dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test React App'
  steps:
  
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Setup Node.js'
  
  - script: npm install
    displayName: 'Install Dependencies'
  
  - script: |
      export CI=true
      npm test -- --watchAll=false --passWithNoTests
    displayName: 'Run Tests'
    continueOnError: true
  
  - script: npm run build
    displayName: 'Build React App'
  
  - script: |
      echo "Starting local server test..."
      timeout 30s npx http-server build -p 3000 &
      sleep 10
      
      if curl -f http://127.0.0.1:3000; then
        echo "✅ Local deployment successful!"
      else
        echo "❌ Local deployment failed"
        exit 1
      fi
    displayName: 'Test Local Deployment'